use chrono::Utc;
use mongodb::bson::oid::ObjectId;
use serde::Serialize;

/// General metadata.
///
/// This should be present in all metadata. Use this with serde's flatten field
/// attribute to store them in a nice readable way.
#[derive(Serialize)]
pub struct GeneralMetadata {
    #[serde(rename = "_id", skip_serializing_if = "Option::is_none")]
    id: Option<ObjectId>,
    created_at: chrono::DateTime<Utc>,
    updated_at: chrono::DateTime<Utc>,
}

/// Generation metadata.
///
/// This is used when AI has generated the content. It contains the most generic
/// information most models use to generate the content it points to.
#[derive(Serialize)]
pub struct GenerationMetadata {
    prompt: String,
    model: String,
}

/// Analysis metadata.
///
/// This is used when AI has analyzed the content.
#[derive(Serialize)]
pub struct AnalysisMetadata {
    title: String,
    tags: Vec<String>,
}

/// Storage metadata.
///
/// This is where the content is stored. This will be used to retrieve the
/// content.
#[derive(Serialize)]
pub enum StorageMetadata {
    /// AWS S3 metadata.
    S3 { bucket: String, key: String },
    /// Azure Blob Storage metadata.
    ABS { container: String, blob: String },
}

/// Chat metadata.
///
/// This is chat generated by AI.
#[derive(Serialize)]
pub struct ChatMetadata {
    #[serde(flatten)]
    general: GeneralMetadata,
    generation: GenerationMetadata,
    analysis: AnalysisMetadata,
}

/// Image metadata.
///
/// This is images generated by AI.
#[derive(Serialize)]
pub struct ImageMetadata {
    #[serde(flatten)]
    general: GeneralMetadata,
    generation: GenerationMetadata,
    analysis: AnalysisMetadata,
    storage: StorageMetadata,
}

/// Video metadata.
///
/// This is video generated by AI.
#[derive(Serialize)]
pub struct VideoMetadata {
    #[serde(flatten)]
    general: GeneralMetadata,
    generation: GenerationMetadata,
    analysis: AnalysisMetadata,
    storage: StorageMetadata,
}

/// Audio metadata.
///
/// This is audio generated by AI.
#[derive(Serialize)]
pub struct AudioMetadata {
    #[serde(flatten)]
    general: GeneralMetadata,
    generation: GenerationMetadata,
    analysis: AnalysisMetadata,
    storage: StorageMetadata,
}
