// Hand-written client for the chat archive/unarchive endpoint.
//
// The rest of this directory is generated by orval from the kamino OpenAPI
// spec (`bun run generate:api`), which reads the spec from a running kamino
// instance. This endpoint — PATCH /api/v1/chats/{id} — isn't in the generated
// client yet. Once the API is regenerated against a kamino build that includes
// it, prefer the generated `updateChat`/`createUpdateChat` and delete this file.

import type { Conversation } from "../models";
import { customFetch } from "../../http/orval-mutator";

export type UpdateChatBody = {
    /** Archive (`true`) or restore (`false`) the conversation. */
    archived: boolean;
};

export const getUpdateChatUrl = (id: string) => `/api/v1/chats/${id}`;

/**
 * Updates mutable fields on a conversation (currently just `archived`).
 * Resolves with the updated conversation, throws on a non-2xx response.
 */
export async function updateChat(
    id: string,
    body: UpdateChatBody,
): Promise<Conversation> {
    const res = await customFetch<{ data: Conversation; status: number }>(
        getUpdateChatUrl(id),
        {
            method: "PATCH",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify(body),
        },
    );
    return res.data;
}
