/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Lerpz AI
 * Lerpz AI backend API
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  HandlerErrorSchema
} from '../models';

import { customFetch } from '../../../lib/orval-mutator';
import type { ErrorType } from '../../../lib/orval-mutator';




/**
 * @summary Get a specific organization
 */
export type handlerResponse200 = {
  data: void
  status: 200
}

export type handlerResponse401 = {
  data: HandlerErrorSchema
  status: 401
}

export type handlerResponse404 = {
  data: HandlerErrorSchema
  status: 404
}

export type handlerResponse500 = {
  data: HandlerErrorSchema
  status: 500
}

export type handlerResponseSuccess = (handlerResponse200) & {
  headers: Headers;
};
export type handlerResponseError = (handlerResponse401 | handlerResponse404 | handlerResponse500) & {
  headers: Headers;
};

export type handlerResponse = (handlerResponseSuccess | handlerResponseError)

export const getHandlerUrl = (id: string,) => {




  return `/api/v1/orgs/${id}`
}

export const handler = async (id: string, options?: RequestInit): Promise<handlerResponse> => {

  return customFetch<handlerResponse>(getHandlerUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getHandlerQueryKey = (id: string,) => {
    return [
    `/api/v1/orgs/${id}`
    ] as const;
    }


export const getHandlerQueryOptions = <TData = Awaited<ReturnType<typeof handler>>, TError = ErrorType<HandlerErrorSchema>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof handler>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getHandlerQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof handler>>> = ({ signal }) => handler(id, { signal });





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof handler>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type HandlerQueryResult = NonNullable<Awaited<ReturnType<typeof handler>>>
export type HandlerQueryError = ErrorType<HandlerErrorSchema>


export function useHandler<TData = Awaited<ReturnType<typeof handler>>, TError = ErrorType<HandlerErrorSchema>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof handler>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof handler>>,
          TError,
          Awaited<ReturnType<typeof handler>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useHandler<TData = Awaited<ReturnType<typeof handler>>, TError = ErrorType<HandlerErrorSchema>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof handler>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof handler>>,
          TError,
          Awaited<ReturnType<typeof handler>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useHandler<TData = Awaited<ReturnType<typeof handler>>, TError = ErrorType<HandlerErrorSchema>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof handler>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get a specific organization
 */

export function useHandler<TData = Awaited<ReturnType<typeof handler>>, TError = ErrorType<HandlerErrorSchema>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof handler>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getHandlerQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Delete a new organization
 */
export type handlerResponse200 = {
  data: void
  status: 200
}

export type handlerResponse401 = {
  data: HandlerErrorSchema
  status: 401
}

export type handlerResponse404 = {
  data: HandlerErrorSchema
  status: 404
}

export type handlerResponse500 = {
  data: HandlerErrorSchema
  status: 500
}

export type handlerResponseSuccess = (handlerResponse200) & {
  headers: Headers;
};
export type handlerResponseError = (handlerResponse401 | handlerResponse404 | handlerResponse500) & {
  headers: Headers;
};

export type handlerResponse = (handlerResponseSuccess | handlerResponseError)

export const getHandlerUrl = (id: string,) => {




  return `/api/v1/orgs/${id}`
}

export const handler = async (id: string, options?: RequestInit): Promise<handlerResponse> => {

  return customFetch<handlerResponse>(getHandlerUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getHandlerMutationOptions = <TError = ErrorType<HandlerErrorSchema>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof handler>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof handler>>, TError,{id: string}, TContext> => {

const mutationKey = ['handler'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof handler>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  handler(id,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type HandlerMutationResult = NonNullable<Awaited<ReturnType<typeof handler>>>

    export type HandlerMutationError = ErrorType<HandlerErrorSchema>

    /**
 * @summary Delete a new organization
 */
export const useHandler = <TError = ErrorType<HandlerErrorSchema>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof handler>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof handler>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getHandlerMutationOptions(options), queryClient);
    }
    /**
 * @summary Update a specific organization
 */
export type handlerResponse200 = {
  data: void
  status: 200
}

export type handlerResponse401 = {
  data: HandlerErrorSchema
  status: 401
}

export type handlerResponse404 = {
  data: HandlerErrorSchema
  status: 404
}

export type handlerResponse500 = {
  data: HandlerErrorSchema
  status: 500
}

export type handlerResponseSuccess = (handlerResponse200) & {
  headers: Headers;
};
export type handlerResponseError = (handlerResponse401 | handlerResponse404 | handlerResponse500) & {
  headers: Headers;
};

export type handlerResponse = (handlerResponseSuccess | handlerResponseError)

export const getHandlerUrl = (id: string,) => {




  return `/api/v1/orgs/${id}`
}

export const handler = async (id: string, options?: RequestInit): Promise<handlerResponse> => {

  return customFetch<handlerResponse>(getHandlerUrl(id),
  {
    ...options,
    method: 'PATCH'


  }
);}




export const getHandlerMutationOptions = <TError = ErrorType<HandlerErrorSchema>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof handler>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof handler>>, TError,{id: string}, TContext> => {

const mutationKey = ['handler'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof handler>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  handler(id,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type HandlerMutationResult = NonNullable<Awaited<ReturnType<typeof handler>>>

    export type HandlerMutationError = ErrorType<HandlerErrorSchema>

    /**
 * @summary Update a specific organization
 */
export const useHandler = <TError = ErrorType<HandlerErrorSchema>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof handler>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof handler>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getHandlerMutationOptions(options), queryClient);
    }
