/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Lerpz AI
 * Lerpz AI backend API
 * OpenAPI spec version: 0.1.0
 */

/**
 * A single message within a conversation.
 */
export interface ConversationMessage {
	/** Raw message text. */
	content: string;
	/** Timestamp when the message was created. */
	created_at: string;
	/** Unique message identifier. */
	id: string;
	/** Message author: `"user"` or `"assistant"`. */
	role: string;
}
