/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Lerpz AI
 * Lerpz AI backend API
 * OpenAPI spec version: 0.1.0
 */

export interface HealthCheck {
	/** Whether the database connection is healthy */
	database: boolean;
	/** Whether the Redis connection is healthy */
	redis: boolean;
}
