/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Lerpz AI
 * Lerpz AI backend API
 * OpenAPI spec version: 0.1.0
 */
import type { Model } from './model';

export interface Models {
  /** List of available AI models */
  models: Model[];
}
