/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Lerpz AI
 * Lerpz AI backend API
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  HandlerErrorSchema
} from '../models';

import { customFetch } from '../../../lib/orval-mutator';
import type { ErrorType } from '../../../lib/orval-mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Create a new image
 */
export type createImageResponse400 = {
  data: HandlerErrorSchema
  status: 400
}

export type createImageResponse401 = {
  data: HandlerErrorSchema
  status: 401
}

export type createImageResponse500 = {
  data: HandlerErrorSchema
  status: 500
}

;
export type createImageResponseError = (createImageResponse400 | createImageResponse401 | createImageResponse500) & {
  headers: Headers;
};

export type createImageResponse = (createImageResponseError)

export const getCreateImageUrl = () => {




  return `/api/v1/images`
}

export const createImage = async ( options?: RequestInit): Promise<createImageResponse> => {

  return customFetch<createImageResponse>(getCreateImageUrl(),
  {
    ...options,
    method: 'POST'


  }
);}




export const getCreateImageMutationOptions = <TError = ErrorType<HandlerErrorSchema>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createImage>>, TError,void, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createImage>>, TError,void, TContext> => {

const mutationKey = ['createImage'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createImage>>, void> = () => {


          return  createImage(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateImageMutationResult = NonNullable<Awaited<ReturnType<typeof createImage>>>

    export type CreateImageMutationError = ErrorType<HandlerErrorSchema>

    /**
 * @summary Create a new image
 */
export const useCreateImage = <TError = ErrorType<HandlerErrorSchema>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createImage>>, TError,void, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createImage>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getCreateImageMutationOptions(options), queryClient);
    }
    /**
 * @summary Create a new image from existing images
 */
export type editImageResponse200 = {
  data: void
  status: 200
}

export type editImageResponse401 = {
  data: HandlerErrorSchema
  status: 401
}

export type editImageResponse500 = {
  data: HandlerErrorSchema
  status: 500
}

export type editImageResponseSuccess = (editImageResponse200) & {
  headers: Headers;
};
export type editImageResponseError = (editImageResponse401 | editImageResponse500) & {
  headers: Headers;
};

export type editImageResponse = (editImageResponseSuccess | editImageResponseError)

export const getEditImageUrl = () => {




  return `/api/v1/images/edit`
}

export const editImage = async ( options?: RequestInit): Promise<editImageResponse> => {

  return customFetch<editImageResponse>(getEditImageUrl(),
  {
    ...options,
    method: 'POST'


  }
);}




export const getEditImageMutationOptions = <TError = ErrorType<HandlerErrorSchema>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof editImage>>, TError,void, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof editImage>>, TError,void, TContext> => {

const mutationKey = ['editImage'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof editImage>>, void> = () => {


          return  editImage(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type EditImageMutationResult = NonNullable<Awaited<ReturnType<typeof editImage>>>

    export type EditImageMutationError = ErrorType<HandlerErrorSchema>

    /**
 * @summary Create a new image from existing images
 */
export const useEditImage = <TError = ErrorType<HandlerErrorSchema>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof editImage>>, TError,void, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof editImage>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getEditImageMutationOptions(options), queryClient);
    }
    /**
 * @summary Delete a specific image
 */
export type deleteImageResponse200 = {
  data: void
  status: 200
}

export type deleteImageResponse401 = {
  data: HandlerErrorSchema
  status: 401
}

export type deleteImageResponse404 = {
  data: HandlerErrorSchema
  status: 404
}

export type deleteImageResponse500 = {
  data: HandlerErrorSchema
  status: 500
}

export type deleteImageResponseSuccess = (deleteImageResponse200) & {
  headers: Headers;
};
export type deleteImageResponseError = (deleteImageResponse401 | deleteImageResponse404 | deleteImageResponse500) & {
  headers: Headers;
};

export type deleteImageResponse = (deleteImageResponseSuccess | deleteImageResponseError)

export const getDeleteImageUrl = (id: string,) => {




  return `/api/v1/images/${id}`
}

export const deleteImage = async (id: string, options?: RequestInit): Promise<deleteImageResponse> => {

  return customFetch<deleteImageResponse>(getDeleteImageUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getDeleteImageMutationOptions = <TError = ErrorType<HandlerErrorSchema>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteImage>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteImage>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteImage'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteImage>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteImage(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteImageMutationResult = NonNullable<Awaited<ReturnType<typeof deleteImage>>>

    export type DeleteImageMutationError = ErrorType<HandlerErrorSchema>

    /**
 * @summary Delete a specific image
 */
export const useDeleteImage = <TError = ErrorType<HandlerErrorSchema>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteImage>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteImage>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getDeleteImageMutationOptions(options), queryClient);
    }
